site_name: Cinemark
repo_url: https://github.com/Requisitos-de-Software/2025.1-Cinemark

nav:
  - Home: index.md

  - Planejamento:
    - Aplicativo Escolhido: planejamento/aplicativo.md
    - Cronograma: planejamento/cronograma.md
    - Ferramentas: planejamento/ferramentas.md
    - Heatmap: planejamento/heatmap.md
    - Metodologia: planejamento/metodologia.md

  - Pré-rastreabilidade:
    - Rich Picture: planejamento/richpicture.md

  - Elicitação:
    - Perfil de Usuário: elicitação/perfilusuario.md
    - Personas: elicitação/personas.md
    - Técnicas de Elicitação:
      - Análise de Interface de Usuário: elicitação/analiseUI.md
      - Introspecção: elicitação/introspecção.md
      - Questionário: elicitação/questionario.md
      - Storytelling: elicitação/storytelling.md
  
    - Técnicas de Priorização:
      - 100$: priorização/100$.md
      - Kano Model: priorização/kanomodel.md
      - MoSCoW: priorização/moscow.md
      - Three Level Scale: priorização/threelevelscale.md
    - Requisitos Elicitados: elicitação/requisitosElicitados.md
  - Apresentação:
    - Entrega 01: apresentações/apresentação-01.md

  - Verificação:
    - Grupo:
      - Entrega 01: verificações/lista-verificação-01.md
      - Entrega 02: verificações/lista-verificação-02.md
    - Grupo+1:
      - Entrega 01: verificações/lista-verificação-01.md
      - Entrega 02: verificações/lista-verificação-02.md

  - Inspeção:
    - Grupo:
      - Entrega 01: inspeções/inspeção-01.md
    - Grupo+1:
      - Entrega 01: inspeções/inspeção-grupo+1-01.md

  - Atas:
    - Reunião 01: atas/Ata Reunião 01.md
    - Reunião 02: atas/Ata Reunião 02.md
    - Reunião 03: atas/Ata Reunião 03.md
    - Reunião 04: atas/Ata Reunião 04.md
    - Reunião 05: atas/Ata Reunião 05.md

theme:
  name: material
  logo: img/logo_cinemark.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-2
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
