site_name: Cinemark
repo_url: https://github.com/Requisitos-de-Software/2025.1-Cinemark

nav:
  - Home: index.md

  - Planejamento:
    - Aplicativo Escolhido: planejamento/aplicativo.md
    - Cronograma: planejamento/cronograma.md
    - Ferramentas: planejamento/ferramentas.md
    - Heatmap: planejamento/heatmap.md
    - Metodologia: planejamento/metodologia.md

  - Pré-rastreabilidade:
    - Rich Picture: planejamento/richpicture.md

  - Elicitação:
    - Perfil de Usuário: elicitação/perfilusuario.md
    - Personas: elicitação/personas.md
    - Técnicas de Elicitação:
      - Análise de Interface de Usuário: elicitação/analiseUI.md
      - Introspecção: elicitação/introspecção.md
      - Questionário: elicitação/questionario.md
      - Storytelling: elicitação/storytelling.md
    - Requisitos Elicitados: elicitação/requisitosElicitados.md
    - Técnicas de Priorização:
      - 100$: priorização/100$.md
      - Kano Model: priorização/kanomodel.md
      - MoSCoW: priorização/moscow.md
      - Three Level Scale: priorização/threelevelscale.md

  - Modelagem:
    - Casos de Uso: modelagem/casosDeUso.md
    - Especificação Suplementar: modelagem/especificaçãoSuplementar.md
    - Cenários: modelagem/cenarios.md
    - Léxicos: modelagem/lexicos.md
    - Modelagem Ágil:
      - NFR Framework: modelagem/nfrFramework.md
      - Backlog: modelagem/backlog.md
      - Histórias de Usuário: modelagem/historias.md

  - Rastreabilidade:
    - Backward-From: rastreabilidade/backward-from.md
    - Forward-From: rastreabilidade/forward-from.md
    - Matriz Geral de Rastreabilidade: rastreabilidade/matriz-geral.md
    - Pós-Rastreabilidade: rastreabilidade/pos-rastreabilidade.md

  - Verificação e Validação:
    - Prototipação: verificacaoValidacao/prototipacao.md
    - Comprovação Informal: verificacaoValidacao/comprovacaoInformal.md

  - Apresentação:
    - Entrega 01: apresentações/apresentação-01.md
    - Entrega 02: apresentações/apresentação-02.md
    - Entrega 03: apresentações/apresentação-03.md
    - Entrega 04: apresentações/apresentação-04.md
    - Entrega 05: apresentações/apresentação-05.md
    - Entrega 06: apresentações/apresentação-06.md

  - Verificação:
    - Grupo:
      - Entrega 01: verificações/lista-verificação-01.md
      - Entrega 02: verificações/lista-verificação-02.md
      - Entrega 03: verificações/lista-verificação-03.md
      - Entrega 04: verificações/lista-verificação-04.md
      - Entrega 05: verificações/lista-verificação-05.md
    - Grupo+1:
      - Entrega 01: verificações/lista-verificação-01+1.md
      - Entrega 02: verificações/lista-verificação-02+1.md
      - Entrega 03: verificações/lista-verificação-03+1.md
      - Entrega 04: verificações/lista-verificação-04+1.md
      - Entrega 05: verificações/lista-verificação-05+1.md

  - Inspeção:
    - Grupo:
      - Entrega 01: inspeções/inspeção-01.md
      - Entrega 02: inspeções/inspeção-02.md
      - Entrega 03: inspeções/inspeção-03.md
      - Entrega 04: inspeções/inspeção-04.md
      - Entrega 05: inspeções/inspeção-05.md
    - Grupo+1:
      - Entrega 01: inspeções/inspeção-grupo+1-01.md
      - Entrega 02: inspeções/inspeção-grupo+1-02.md
      - Entrega 03: inspeções/inspeção-grupo+1-03.md
      - Entrega 04: inspeções/inspeção-grupo+1-04.md
      - Entrega 05: inspeções/inspeção-grupo+1-05.md

  - Atas:
    - Reunião 01: atas/Ata Reunião 01.md
    - Reunião 02: atas/Ata Reunião 02.md
    - Reunião 03: atas/Ata Reunião 03.md
    - Reunião 04: atas/Ata Reunião 04.md
    - Reunião 05: atas/Ata Reunião 05.md
    - Reunião 06: atas/Ata Reunião 06.md
    - Reunião 07: atas/Ata Reunião 07.md
    - Reunião 08: atas/Ata Reunião 08.md

theme:
  name: material
  logo: img/logo_cinemark.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-2
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
